teams:
- name: karmada-adopter-group
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - CharlesQQ
  - dongjiang1989
  - guozheng-shen
  - ivan-cai
  - LivingCcj
  - NickYadance
  - stulzq
  - vie-serendipity
  - yangsoon
  - zach593
- name: repo-admins
  maintainers:
  - kevin-wangzefeng
  - RainbowMango
  members:
  - karmada-bot
repositories:
- name: api
  teams:
    repo-admins: admin
  visibility: public
- name: community
  teams:
    repo-admins: admin
  visibility: public
- name: dashboard
  teams:
    repo-admins: admin
  visibility: public
- name: karmada
  teams:
    repo-admins: admin
  visibility: public
- name: kubernetes
  teams:
    repo-admins: admin
  visibility: public
- name: multi-cluster-ingress-nginx
  teams:
    repo-admins: admin
  visibility: public
- name: multicluster-cloud-provider
  teams:
    repo-admins: admin
  visibility: public
- name: playground
  teams:
    repo-admins: admin
  visibility: public
- name: website
  teams:
    repo-admins: admin
  visibility: public
